name: openvpn-server
services:
  openvpn:
    image: rimorgin/openvpn
    container_name: openvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true
    ports:
      - "1194:1194/udp"
    environment:
      #- OPENVPN_CLIENT_FILENAME=rimorgin
      - OPENVPN_SERVER_IP=10.15.20.34
    devices:
      - /dev/net/tun
    volumes:
      - ./data:/data
    